### PR TITLE
Feat  subscription and favorites

### PR DESCRIPTION
**Pull request by derrxb**
This PR should be reviewed after https://github.com/KED-2020/api-mind-map/pull/10 since it builds from where I left off there. This PR does two main things:

- [x] Setup the favourites API endpoint: This is completed using a `many-to-many` relationship between the existing documents table and the inbox. I'm not sure if this is the best approach but it works.
- [x] Setup subscriptions table and link to an inbox: This is done using a new `subscriptions` table that is linked to the inbox table in a `one-to-many` relationship.
- [x] Add specs: There's one spec called 'should return a documents lists when documents exist for an inbox' or something like that that is failing. I'm aware of this and will fix it in a later PR. Specs for the subscriptions will be added in a later PR when we actually add the functionality.

The main idea of this PR is the setup both the favourites and the subscriptions table. While working on it, I changed a few things though since it made the work easier.

### CODE REVIEW

**Comment by derrxb** [comment]
Oops, specs blew up. I will fix this asap.

**Comment by Kyeg** [comment]
This is my testing, there is one Failure, is it normal or I should do some configuration before testing?

```
$ rake spec:all

Run options: --seed 31194

# Running:

...........SS..........F........

Finished in 1.311295s, 24.4034 runs/s, 86.1744 assertions/s.

  1) Failure:
Test API routes::Get inbox documents route#test_0002_should return an documents lists when they exists for an inbox [/Users/kyeg_logos_mac/GitHub_Box/api-mind-map/spec/tests_acceptance/api_spec.rb:202]:
Expected: 1
  Actual: 0

32 runs, 113 assertions, 1 failures, 0 errors, 2 skips

You have skipped tests. Run with --verbose for details.
Coverage report generated for RSpec to /Users/kyeg_logos_mac/GitHub_Box/api-mind-map/coverage. 985 / 1051 LOC (93.72%) covered.
rake aborted!
Command failed with status (1)

Tasks: TOP => spec:all
(See full trace by running task with --trace)
```

**Comment by derrxb** [comment]
This branch is outdated. You should run the master as it has the latest updates

**Comment by Kyeg** [comment]
So in the #12, every test on the api will be passed?

**Comment by Kyeg** [comment]
Oh, I saw it: https://github.com/KED-2020/api-mind-map/pull/12
It seems checked by GitHub Action.
Ok, then I have no problem.

**Pull request merged**
