### PR TITLE
Inbox create

### PR DESCRIPTION
**Pull request by derrxb**

### CODE REVIEW

**Comment by Kyeg** [comment]
I am on the latest `inbox-create branch`.
```
> git st

On branch inbox-create
Your branch is up to date with 'origin/inbox-create'.
```

It seems two tests cannot be passed.
```
> rake spec:all

Run options: --seed 19760

# Running:

............F...........F...

Finished in 1.151446s, 24.3172 runs/s, 91.1897 assertions/s.

  1) Failure:
GetInbox integration tests::Get an Inbox#test_0001_HAPPY: should return inbox and their suggestions [/Users/kyeg_logos_mac/GitHub_Box/api-mind-map/spec/tests_integration/service_integration/get_inbox_spec.rb:44]:
Expected: 30
  Actual: 0

  2) Failure:
Test API routes::Get inboxes route#test_0001_should return a the requested inbox [/Users/kyeg_logos_mac/GitHub_Box/api-mind-map/spec/tests_acceptance/api_spec.rb:101]:
Expected: 30
  Actual: 0

28 runs, 105 assertions, 2 failures, 0 errors, 0 skips
Coverage report generated for RSpec to /Users/kyeg_logos_mac/GitHub_Box/api-mind-map/coverage. 919 / 956 LOC (96.13%) covered.
rake aborted!
Command failed with status (1)

Tasks: TOP => spec:all
(See full trace by running task with --trace)
```

**Comment by Kyeg** [comment]
By the way, I guess this line has some problems.

https://github.com/KED-2020/api-mind-map/blob/f31462eee57e1d0e663326826dfb0a99cc1ebce1/.github/workflows/api.yml#L43

Because `$ rake spec` has no means in our Rakefile.
I think this part should be `$ rake spec:all`

Now, this GitHub Action testing should always pass (because `$ rake spec` has no means).

**Comment by derrxb** [comment]
I didn't write the code with the `rake spec`. That's something @eslywadan wrote in the master

**Comment by derrxb** [comment]
Can you try running the tests again? I did a recent push to master like less than 5 mins ago? @Kyeg

**Comment by Kyeg** [comment]
Ok, thanks. I think everything is solved.

```
rake spec:all
Run options: --seed 36092

# Running:

............................

Finished in 1.280005s, 21.8749 runs/s, 85.1559 assertions/s.

28 runs, 109 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for RSpec to /Users/kyeg_logos_mac/GitHub_Box/api-mind-map/coverage. 922 / 958 LOC (96.24%) covered.
```

**Review by Kyeg — APPROVED** [review]

**Pull request merged**
